# Site settings
title: "jennyhu"
logo: logo.png
email: 839460688@qq.com
description: 好记性不如赖笔头
url: "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/


# Build settings
markdown: redcarpet
