# Site settings
title: "jennyhu"
logo: logo.png
email: 839460688@qq.com
description: 好记性不如赖笔头
url: "" # the base hostname & protocol for your site
baseurl: "/blog" # the subpath of your site, e.g. /blog/


# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]